### ISSUE TITLE
Uzávorkovat kvantifikátory jednoznačně

### ISSUE THREAD

**Issue by malinajan** [Krejdom/school_notes#4]
Ahoj,
v IB101 píšeš:

```
¬∀xP(x) ⇔ ∃x¬P(x)
¬∃xP(x) ⇔ ∀x¬P(x)
```

Pokud je záměrem, aby materiály byly korektní a použitelné i do budoucna (pro ostatní), doporučuji pro jednoznačnost psát:

```
¬(∀xP(x)) ⇔ ∃x¬P(x)
¬(∃xP(x)) ⇔ ∀x¬P(x)
```

Pokud chceš, mohu vyrobit fork a pull request, u takové drobnosti mi to ale přijde skoro zbytečné...

**Comment by Krejdom** [comment]
Díky za připomínku. Opraveno. :)
